MIXTTAPE/mixttape-front-end

- package-lock.json
- package.json
- src/actions/searchActions.js
- src/actions/searchActions.test.js
- src/components/App.js
- src/components/__snapshots__/App.test.js.snap
- src/reducers/searchReducer.js
- src/reducers/searchReducer.test.js
- Created `songReducer.js` and `songActions.js` files.
- Created action for ADD_SONG
- Created case in reducer for handling adding a song
- Wrote passing tests for each
> Created songReducer.js and songActions.js

- src/actions/searchActions.js
- src/actions/searchActions.test.js
- src/reducers/searchReducer.js
- src/reducers/searchReducer.test.js
- Added in DELETE_SONG case to `songReducer.js`
- Added action to handle DELETE_SONG
- wrote passing tests for all
> Added DELETE_SONG case to songReducer.js

- src/selectors/mixtapeSelectors.js
- src/selectors/mixtapeSelectors.test.js
- Wrote getUserMixtapes() and getLastEditedMixtapes() selectors
- wrote passing tests
> Wrote getUserMixtapes() and getLastEditedMixtapes() selectors

- package-lock.json
- package.json
- src/components/editTape/EditTape.js
- src/components/mixtapeSong/MixtapeSong.js
- src/index.js
- src/reducers/editedMixtapeReducer.js
- src/reducers/editedMixtapeReducer.test.js
- src/reducers/index.js
- src/store.js
Selector still needs to be implemented to grab the mixtape for editing from state. Reducer store implemented, as well as global redux provider.
> Create edit list

- src/actions/editedMixtapeActions.js
- src/reducers/activeMixtapeReducer.js
- src/reducers/activeMixtapeReducer.test.js
- src/reducers/editedMixtapeReducer.js
- src/reducers/editedMixtapeReducer.test.js
- src/reducers/index.js
- src/reducers/userReducer.js
- src/reducers/userReducer.test.js
- All reducers working and tested (passing)
> Completed Reducers

- scratch/soundcloud-iFrame
- src/components/searchResultSection/SearchResultSection.js
- src/components/searchSongs/SearchSongs.js
- src/services/masterApiCall.js
- src/services/soundcloud.js
- src/services/youtube.js
Live youtube results render properly. Need to make a new component for soundcloud results.
> Search service integration

- src/components/searchResultSection/SoundcloudSearchResultSection.js
- src/components/searchResultSection/YoutubeSearchResultSection.js
- src/components/searchResultSectionItem/SearchResultSectionItem.js
- src/components/searchSongs/SearchSongs.js
- src/reducers/editedMixtapeReducer.js
- src/services/masterApiCall.js
- src/services/soundcloud.js
Dependent on soundcloud result section branch. Songs from search results add to global state correctly. Next step: Create -> Edit list should read the mixtape for editing from state and render songs.
> Add song to edit

- src/components/editTape/EditTape.js
- src/components/mixtapeSong/MixtapeSong.js
- src/components/searchResultSection/SoundcloudSearchResultSection.js
- src/components/searchResultSection/YoutubeSearchResultSection.js
- src/components/searchSongs/SearchSongs.js
- src/reducers/editedMixtapeReducer.js
- src/reducers/editedMixtapeReducer.test.js
Songs added from search appear in the edit mixtape list. Deleting implemented. Need user backend to start saving multiple playlists.
> Edit mixtape

- package-lock.json
- package.json
- src/components/header/Header.js
- src/components/mixt/Mixt.js
- src/components/nav/Nav.js
- src/components/player/Player.js
- src/styles/global.css
- src/styles/header.css
- src/styles/nav.css
- src/styles/player.css
- webpack.config.js
- updated HTML in `Header.js`, `Nav.js`, and `Player.js` components
- created a `global.css` stylesheet for global styles
- created stylesheets for `Header.js`, `Nav.js`, and `Player.js` components and styled with basic setup
- installed `react-icons` package to utilize font awesome icons in `Player.js`
> Header and Player Component Styling

- package-lock.json
- package.json
- src/components/App.js
- src/components/__snapshots__/App.test.js.snap
- src/components/mixt/Mixt.js
- src/components/splash/Splash.js
- src/styles/player.css
- Setup of basic routes for all views of the app
- installed `react-router-dom` so that it all works
- updated styling on `player.js` to `position:fixed` from `position:sticky` for better usability.
- updated the splash page's content
> Initial Router setup

- src/components/create/Create.js
- src/components/editTape/EditTape.js
- src/components/mixtapeSong/MixtapeSong.js
- src/components/searchResultSection/SoundcloudSearchResultSection.js
- src/components/searchResultSection/YoutubeSearchResultSection.js
- src/components/searchResultSectionItem/SearchResultSectionItem.js
- src/components/searchSongs/SearchSongs.js
- src/styles/create.css
- src/styles/global.css
- src/styles/helpers.css
- src/styles/styles.css
- Did a bunch of shifting to files to get the `Create` component looks very nice.
> Initial Styling of Create.js Component

- src/components/loginSignUp/Login.js
- src/components/loginSignUp/SignUp.js
- src/components/splash/Splash.js
- src/styles/create.css
- src/styles/global.css
- src/styles/splash.css
- Getting Login and Sign up all situated on `Splash.js` along with some light styling updates.
> Finalizing Splash Page

- src/actions/editedMixtapeActions.js
- src/actions/editedMixtapeActions.test.js
- src/actions/userActions.test.js
- src/components/loginSignUp/Login.js
- src/components/loginSignUp/SignUp.js
- src/reducers/editedMixtapeReducer.js
- src/reducers/editedMixtapeReducer.test.js
- src/reducers/userReducer.js
- src/reducers/userReducer.test.js
- src/services/__mocks__/mixtapeApi.js
- src/services/auth.js
- src/services/mixtapeApi.js
- src/services/request.js
Reducer updates so that user and edited playlist store in DB before updating state.
> Reducer updates

- package-lock.json
- package.json
- scratch/fake-mixtape.js
- src/components/player/Player.js
- src/components/player/ReactPlayer.js
- src/styles/player.css
- Used the `react-player` npm package to create basic player controls, playlist setup, and functionality.
- Using fake data to function. Will need to be moved over to `activeMixtape` state in the future
> MVP Player Functionality

- scratch/fake-mixtape.js
- src/actions/activeMixtapeActions.js
- src/actions/activeMixtapeActions.test.js
- src/components/mixt/Mixt.js
- src/components/player/Player.js
- src/components/tapeDetail/TapeDetail.js
- src/reducers/activeMixtapeReducer.js
- src/reducers/activeMixtapeReducer.test.js
- src/selectors/activeMixtapeSelectors.js
- src/selectors/activeMixtapeSelectors.test.js
- src/styles/header.css
- src/styles/nav.css
- src/styles/styles.css
- src/styles/tape-detail.css
- Rendering a Detail View based on mocked data.
- moved playing into the reducer so it's globally accessible.
- had to update all tests, reducer, actions, selectors (so there's a lot of changed files)
- created play button in mixtape detail view to start current playlist
> Mixtape Detail View

- src/components/mediaRecorder/MediaRecorder.js
- src/components/nav/Nav.js
- src/styles/nav.css
- Added in react-router-dom Links to the nav. The app is now navigable and music play persists!
> Setup Nav Links (LOGOUT NOT FUNCTIONAL)

- src/actions/userActions.js
- src/components/editTape/EditTape.js
- src/components/loginSignUp/Login.js
- src/components/loginSignUp/SignUp.js
- src/reducers/editedMixtapeReducer.js
- src/selectors/userSelectors.js
> Save mixtape fix

- src/actions/activeMixtapeActions.js
- src/actions/activeMixtapeActions.test.js
- src/components/tapeDetail/TapeDetail.js
- src/reducers/activeMixtapeReducer.js
- src/reducers/activeMixtapeReducer.test.js
- src/selectors/activeMixtapeSelectors.js
- src/selectors/activeMixtapeSelectors.test.js
- src/services/__mocks__/mixtapeApi.js
- src/services/mixtapeApi.js
Mixtape detail page fetches via ID on page load
> Mixtape detail

- src/components/mediaRecorder/MediaRecorder.js
- src/components/player/Player.js
- Voice memos are fully functioning
> Adding Voice Memos to Player

- src/components/App.test.js
- src/components/editTape/EditTape.js
- src/components/loginSignUp/Login.js
- src/components/loginSignUp/SignUp.js
> Redirect on login and signup

- scratch/MediaRecorder.js
- src/components/mediaRecorder/MediaRecorder.js
- src/styles/create.css
- src/styles/global.css
- Styled the voice memo section
- styled the Mixtape Name input
> Styling on Create View

- src/components/player/Player.js
- src/styles/player.css
> Fixed Moving Controls in Player Bug

- src/components/editTape/EditTape.js
- src/components/loginSignUp/Login.js
- src/components/loginSignUp/SignUp.js
- src/components/mediaRecorder/MediaRecorder.js
- src/components/searchResultSectionItem/SearchResultSectionItem.js
Checked all the components and made sure prop types were established.
>  all components props have been validated and verified

- src/components/editTape/EditTape.js
- src/components/mediaRecorder/MediaRecorder.js
- src/components/player/Player.js
- src/components/tapeDetail/TapeDetail.js
- src/components/tapeList/TapeList.js
- src/styles/tape-detail.css
- Voice Memo Icons renders everywhere
- Left side detail on detail view sticks
- fixed a lot of key warning issues
- turned off fake player data
> Various Fixes for Front End

- src/components/nav/Nav.js
- src/components/tapeList/TapeList.js
- Log out button is now functional
> Log Out Button Functional

- src/components/editTape/EditTape.js
- src/reducers/userReducer.js
- src/reducers/userReducer.test.js
- src/selectors/userSelectors.js
save now properly takes a single click, and redirects to the most recently created mixtape.
> Save bug smasher

- src/actions/userActions.js
Added catch to setUserSignup to display backend errors for password length
> Password Length required

- src/components/create/Create.js
- src/components/tapeDetail/TapeDetail.js
- src/components/tapeList/TapeList.js
- src/styles/global.css
- Centered loading and "no mixtapes" h3s
> Centering Loading State

- src/components/create/Create.js
- src/components/nav/Nav.js
- src/components/tapeDetail/TapeDetail.js
- src/components/tapeList/TapeList.js
- See title
- Removed semi colon from loading section (typo)
> Nav shows sign up and login links if user is not authenticated

- src/components/tapeList/TapeList.js
- src/styles/tape-list.css
- Styled Delete Mixtape button
> Delete Mixtape Button Styles

- src/reducers/editedMixtapeReducer.test.js
more test coverage for state. Yay!
> test written for editedMixtapeReducer, test passes

- src/components/player/Player.js
- src/components/tapeDetail/TapeDetail.js
- src/components/tapeList/TapeList.js
- src/reducers/activeMixtapeReducer.js
- src/selectors/activeMixtapeSelectors.js
- src/selectors/activeMixtapeSelectors.test.js
Now when a user plays a mixtape it resets the index to 0 so we don't start the next mixtape at whatever the previous mixtape index was. Also auto plays every time a mixtape is selected now.
> Mixtape index bug

- src/actions/activeMixtapeActions.test.js
- src/reducers/activeMixtapeReducer.test.js
- src/selectors/activeMixtapeSelectors.test.js
> Active mixtape reducer tests

- src/components/aboutUs/AboutUs.js
- src/components/aboutUs/__snapshots__/AboutUs.test.js.snap
- src/styles/tape-detail.css
> updating about us snapshot

- package-lock.json
- package.json
- src/components/searchResultSectionItem/SearchResultSectionItem.js
Youtube results no longer have html symbol substitutes.
> Decode bugfix

- src/actions/activeMixtapeActions.js
- src/components/aboutUs/__snapshots__/AboutUs.test.js.snap
- src/components/tapeDetail/TapeDetail.js
- src/reducers/activeMixtapeReducer.js
- src/reducers/activeMixtapeReducer.test.js
- src/reducers/userReducer.test.js
- src/selectors/activeMixtapeSelectors.js
- src/selectors/activeMixtapeSelectors.test.js
fetching a mixtape will now not look like loading
> Fail fetch bug

- src/components/mediaRecorder/MediaRecorder.js
- Voice memo thumbnail should appear in production now.
> Fixing Voice Memo Thumbnail Issue

- src/components/mediaRecorder/MediaRecorder.js
- src/components/mixtapeSong/MixtapeSong.js
> Media Recorder Emergency Fix

- src/components/tapeDetail/TapeDetail.js
User persists on reload via verify.
> user persists in detail view if logged in on refresh

- src/actions/userActions.js
- src/components/loginSignUp/SignUp.js
- src/components/player/Player.js
- src/components/player/Player.test.js
- src/components/searchResultSection/YoutubeSearchResultSection.js
- src/components/searchSongs/SearchSongs.js
- src/reducers/userReducer.js
- src/services/masterApiCall.js
- src/services/soundcloud.js
- Cleaning out some unused code
- I removed the soundcloud results because our fetch call is no longer working. The app is non functioning for a user until we fix it, so I removed them temporarily (I have a potentially employer looking at this app this week).
> Only Rendering Youtube Results until Soundcloud is Fixed

- src/components/searchResultSection/SoundcloudSearchResultSection.js
- src/components/searchResultSection/YoutubeSearchResultSection.js
- src/components/searchSongs/SearchSongs.js
- src/services/masterApiCall.js
- src/services/soundcloud.js
- We fixed soundcloud! (for now)
> Soundcloud is Back!

- src/components/editTape/EditTape.js
- src/components/searchResultSectionItem/SearchResultSectionItem.js
- src/styles/create.css
- src/styles/tape-detail.css
- src/styles/tape-list.css
> Removing unnecessary comments from master brand

- src/components/searchSongs/SearchSongs.js
- src/services/masterApiCall.js
> Removing More Code Comments
